# Generated by Django 2.2.6 on 2019-10-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='petition_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone_number', models.IntegerField()),
                ('reason', models.CharField(max_length=1000)),
                ('have_pet', models.BooleanField(null=True)),
            ],
        ),
    ]
