# Generated by Django 2.2.6 on 2019-10-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0002_auto_20191016_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition_entry',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
