# Generated by Django 2.2.6 on 2019-10-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0003_auto_20191016_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescue_entry',
            name='dog_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='rescue_entry',
            name='identification_mark',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='rescue_entry',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rescue_entry',
            name='scenario',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
