# Generated by Django 2.2.6 on 2019-10-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0004_auto_20191016_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescue_entry',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
