# Generated by Django 2.2.6 on 2019-11-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0005_auto_20191016_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescue_entry',
            name='lat_position',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rescue_entry',
            name='long_position',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
    ]
