# Generated by Django 2.2.6 on 2019-11-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0006_auto_20191102_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescue_entry',
            name='lat_position',
            field=models.DecimalField(decimal_places=10, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='rescue_entry',
            name='long_position',
            field=models.DecimalField(decimal_places=10, max_digits=14, null=True),
        ),
    ]
