# Generated by Django 2.2.6 on 2019-11-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0007_auto_20191102_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescue_entry',
            name='lat_position',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rescue_entry',
            name='long_position',
            field=models.FloatField(null=True),
        ),
    ]
