# Generated by Django 2.2.6 on 2019-11-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0008_auto_20191102_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescue_entry',
            name='lat_position',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rescue_entry',
            name='long_position',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
